Sprint 1/step 2
foxoter/react-burger pull request #2
Opened 2021-07-02 12:32 UTC by foxoter

2021-07-05 10:28 UTC, SmilingJey requested changes
Здравствуйте, Булат!

Хорошая работа, приложение почти полностью соответсвует макету, необходимый функционал работает, реализовано открытие попапа в портале. Но есть несколько замечаний:

**Нужно исправить:**

- по макету подложка попапа долдна быть полупрозразной 

- в компонент Modal передавайте текст заголовка как пропс

- закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal

- в компоненте ModalOverlay  не нужно использовать портал

- в компоненте BurgerConstructor используйте useMemo,а не хук useEffect + сейт setOrderTotal

- при получении данных с сервера добавьте проверку, что запрос выполнился успешно

- в проекте используется именование в стиле kebab-case для файлов, назовите файл компонента App так же с маленькой буквы app.tsx

**Места, в которых можно улучшить проект:**

- в попапах размер шрифта не везде соответвует макету

- описание запросов к серверу лучше вынести в функции в отдельный файл api и брать функции их из него

- вместо функции renderIngredientsSection создайте отдельный компонент

- в HeaderItem  передавайте компонент иконки как пропс, а не хардкодте через switch

Подробнее замечания описаны ниже в комментариях к самим участкам кода:

2021-07-05 10:28 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.tsx
> +  useEffect(() => {
**Надо исправить**

здесь нужен хук useMemo, который будет выполнять перерасчет при изменении pickedItems ,а не хук useEffect + сейт setOrderTotal


```
const orderTotal= useMemo(() => {
      if (pickedItems.length) return 0;
      return pickedItems.reduce((sum, current) => sum += current.price, 0);
}), [pickedItems]);
```

2021-07-05 10:28 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.tsx
> +  useEffect(() => {
**Надо исправить**

закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal

2021-07-05 10:28 UTC, SmilingJey commented on src/components/burger-ingridients/burger-ingredients.tsx
> +  useEffect(() => {
**Надо исправить**

закрытие попапа по ESC относится к функционалу модального окна и должно быть описано в компоненте Modal

2021-07-05 10:28 UTC, SmilingJey commented on src/components/burger-ingridients/burger-ingredients.tsx
> +  const renderIngredientsSection = (ingredient: string) => {
**Можно лучше**

лучше вынести в отдельный компонент

2021-07-05 10:28 UTC, SmilingJey commented on src/components/header-item/header-item.tsx
>        case('Конструктор'):
**Можно лучше**

передавайте компонент иконки как пропс, а не хардкодте через switch

2021-07-05 10:28 UTC, SmilingJey commented on src/components/modal/modal.tsx
> +          <p className={`${modalStyles.heading} text text_type_main-medium`}>Детали ингердиента</p>
**Надо исправить**

передавайте текст заголовка как пропс

2021-07-05 10:28 UTC, SmilingJey commented on src/components/modal-overlay/modal-overlay.tsx
> +  return modalsRoot ? ReactDOM.createPortal(
**Надо исправить**

ReactDOM.createPortal здесь не нужен т.к. ModalOverlay используется внутри Modal, который и так внутри портала рендерится

2021-07-05 10:28 UTC, SmilingJey commented on src/components/modal-overlay/modal-overlay.tsx
> +function ModalOverlay(props: Props) {
**Надо исправить**

по макету подложка попапа долдна быть полупрозразной 
![Screenshot_2](https://user-images.githubusercontent.com/9317133/124457789-e1e96600-dd94-11eb-96e6-d046b5fd1e06.png)

2021-07-05 13:05 UTC, foxoter commented on src/components/burger-constructor/burger-constructor.tsx
> +  useEffect(() => {
Класс, спасибо!

2021-07-05 13:08 UTC, foxoter commented on src/components/burger-constructor/burger-constructor.tsx
> +  useEffect(() => {
Спасибо. Удивляюсь, как я не догадался об этом.

2021-07-05 13:37 UTC, foxoter commented on src/components/modal-overlay/modal-overlay.tsx
> +function ModalOverlay(props: Props) {
Не понял, что такое подложка попапа. Это само окошко с контентом или его фон ?

Если фон (то есть сам `ModalOverlay`), он у меня полупрозрачный: [ссылка на стили](https://github.com/foxoter/react-burger/blob/sprint-1/step-2/src/components/modal-overlay/modal-overlay.styles.module.css#L4)

Если само окошко сделать полупрозрачным, то получается странно: 
![image](https://user-images.githubusercontent.com/60886917/124479645-27b32800-ddaf-11eb-8b64-3d3102a039c3.png)

2021-07-05 13:52 UTC, foxoter commented on src/components/header-item/header-item.tsx
>        case('Конструктор'):
Я не понимаю, как это сделать, учитывая, что у меня в `AppHeader` с помощью `map` создаются эти пункты меню.

Лучше их захардкодить?

2021-07-05 14:01 UTC, foxoter commented on src/components/burger-ingridients/burger-ingredients.tsx
> +  const renderIngredientsSection = (ingredient: string) => {
Спасибо. Возможно, реализую позже.

2021-07-06 09:06 UTC, SmilingJey commented on src/components/header-item/header-item.tsx
>        case('Конструктор'):
Делается это так:

menu-titles-data.js
```
import { BurgerIcon, ListIcon, ProfileIcon } from '@ya.praktikum/react-developer-burger-ui-components';

export const menuItems = [
    { title: 'Конструктор', Icon: BurgerIcon },
    { title: 'Лента заказов', Icon: ListIcon },
    { title: 'Личный кабинет', Icon: ProfileIcon }
];
```

app-header.tsx
```
        <HeaderItem
          key={idx}
          title={item.title}
          Icon={item.Icon}
        />
```

header-item.tsx
```
function HeaderItem(props: Props) {
  const { title, isActive, Icon } = props;
  const uiKitStyles = {
    listItem: 'pl-5 pr-5',
    text: 'ml-2 text text_type_main-medium',
  }

  const renderIcon = () => {
    const type = isActive ? 'primary' : 'secondary'
    return <Icon type={type}/>
  }
..............
```

Таким образов в HeaderItem мы можем передать требуемую иконку

2021-07-06 09:07 UTC, SmilingJey commented on src/components/modal-overlay/modal-overlay.tsx
> +function ModalOverlay(props: Props) {
Имелась ввиду прозрачность ModalOverlay, сейчас отображается корректно, в прошлый раз ModalOverlay почему то был не прозразный

2021-07-06 09:17 UTC, SmilingJey approved these changes
Отлично, критические замечания исправлены

Оставил пример, как в header-item передать иконку в пропс

Забыл отметить напрошлом ревью:
Файлы стилей обычно назваются без слова styles, например `app-header.module.css`

Так же в проекте советую использовать для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

И не забывайте оборачивать вычисления которые производятся в функции рендеринга в useMemo, что бы рассчеты выполнялись только при необходимости, а не при каждом рендере

2021-07-06 09:30 UTC, foxoter commented on src/components/header-item/header-item.tsx
>        case('Конструктор'):
Спасибо, понял.

2021-07-06 09:34 UTC, foxoter commented on src/components/header-item/header-item.tsx
>        case('Конструктор'):
Если честно, впервые вижу такой приём, круто, спасибо.

2021-07-06 09:43 UTC, merged