Sprint 2/step 2
foxoter/react-burger pull request #3
Opened 2021-07-16 16:13 UTC by foxoter

2021-07-19 20:19 UTC, AygulMalikova requested changes
Наша команда приносит извинения за долгое ожидание проверки. 
Отличная работа! У вас хорошо структурированный и чистый код, разделенный на компоненты, весь необходимый функционал реализован и работает верно!

Но есть небольшие замечания. Пожалуйста, разделите ваш редьюсер на несколько по функционалу и переместите создание rootReducer в отдельный файл. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-19 20:19 UTC, AygulMalikova commented on src/services/reducers/index.ts
> +      }
Можно лучше:

Здесь вы также можете добавить `ingredientsFailed: false`, чтобы сбросить предыдущее состояние с ошибками

2021-07-19 20:19 UTC, AygulMalikova commented on src/services/reducers/index.ts
> +    }
Надо исправить:

Несмотря на то, что в задании сказано: "На этом этапе мы рекомендуем собрать все редьюсеры в одном файле", вам следует разделить редьюсеры на несколько по функционалу (и пока что разметить в одном файле), т.к. хранить все в одном редьюсере - не самый лучший подход.

2021-07-20 11:46 UTC, AygulMalikova approved these changes
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-07-20 12:28 UTC, foxoter commented
Спасибо за ревью!

2021-07-20 12:28 UTC, merged